### ISSUE TITLE
Does not compile as a dependency with Nix

### ISSUE THREAD

**Issue by noaccOS** [saleyn/typedstruct#1]
I am trying to use this as a dependency for a project I am building with Nix, but unfortunately the compilation fails for v0.5.2 (works fine with v0.5.0)

The problem seems to be from the from the `vsn` function in `mix.exs`.

This is the log:
```
error: builder for '/nix/store/498xcjv002wcm4b61lv9ib5fs8cgzf6a-mix-release-metadata-0.0.1.drv' failed with exit code 1;
       last 10 log lines:
       > updateAutotoolsGnuConfigScriptsPhase
       > configuring
       > Error while loading project :typedstruct at /build/deps/typedstruct
       > ** (RuntimeError) Cannot determine application version!
       >     /build/deps/typedstruct/mix.exs:144: TypedStruct.MixProject.vsn/0
       >     /build/deps/typedstruct/mix.exs:8: TypedStruct.MixProject.project/0
       >     (mix 1.15.7) lib/mix/project.ex:938: Mix.Project.get_project_config/1
       >     (mix 1.15.7) lib/mix/project.ex:205: Mix.Project.push_config/2
       >     (mix 1.15.7) lib/mix/project.ex:168: Mix.Project.push/3
       >     (stdlib 5.1.1) lists.erl:1594: :lists.foldl/3
       For full logs, run 'nix log /nix/store/498xcjv002wcm4b61lv9ib5fs8cgzf6a-mix-release-metadata-0.0.1.drv'.
```

I am fetching the dependencies with [`fetchMixDeps`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/beam-modules/fetch-mix-deps.nix) and using them as parameter for [`mixRelease`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/beam-modules/mix-release.nix) as described in [the manual](https://nixos.org/manual/nixpkgs/stable/#mix-release-example)

**Comment by jozuas** [comment]
See `nix log /nix/store/498xcjv002wcm4b61lv9ib5fs8cgzf6a-mix-release-metadata-0.0.1.drv` for more detailed output.

My guess is that the "cannot determine application version" is coming from the usage of the `git` executable. https://github.com/saleyn/typedstruct/blob/7a73f896eed9b792d7ef4e94c0833e5831751392/mix.exs#L126

My guess would be that adding `git` to your build dependencies would fix the problem.

**Comment by noaccOS** [comment]
> See nix log /nix/store/498xcjv002wcm4b61lv9ib5fs8cgzf6a-mix-release-metadata-0.0.1.drv for more detailed output.

It's only showing the `mkDerivation` steps, but the failure log is the same

> My guess would be that adding git to your build dependencies would fix the problem.

The nix fetcher specifically removes the git directory [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/beam-modules/fetch-mix-deps.nix#L56) so even that doesn't work unfortunately

**Comment by dluksza** [comment]
It looks like the `vsn()` is evaluated when the dependencies are compiled. With `{:typedstruct, "0.5.2"}` I'm getting the following error when I try to start iex:

```
** (Mix) Expected :version to be a valid Version, got: "bbf4846" (see the Version module for more information)
```

the `bbf4846` is **my local HEAD**. Switching to `0.5.0` gives a different error message:

```
Unchecked dependencies for environment dev:
* typedstruct (Hex package)
  the dependency does not match the requirement "0.5.0", got "0.5.0-dev+bbf4846-dirty"
** (Mix) Can't continue due to errors on dependencies
```

but at least that one is evaluated in the context of `typedstruct` repository.

Would it be possible to release `0.5.3` with a hardcoded version?

**Comment by tor-oscar** [comment]
This did not compile as a dependency at all for me. Updating how the `.hex` file is found fixes it. Made a PR https://github.com/saleyn/typedstruct/pull/4.

**Comment by procmarchal** [comment]
I have a similar issue on an umbrella project. When compiling from sub-project, it does not manage to resolve the version.
```
Unchecked dependencies for environment dev:
* typedstruct (Hex package)
  the dependency does not match the requirement "~> 0.5.2", got "1.4.1-8559-g2c7c3d0dfa"
** (Mix) Can't continue due to errors on dependencies
```

**Comment by adamcstephens** [comment]
I'm using deps_nix and fix this with an override. Though ideally this would be fixed permanently in this repository. I'm not sure the reasoning behind the version detection logic, but it fails in multiple scenarios when using nix.

```
mixNixDeps = callPackages ./deps.nix {
  inherit lib beamPackages;
  overrides = self: prev: {
    typedstruct = prev.typedstruct.override (old: {
      postPatch = ''
        substituteInPlace mix.exs --replace-fail 'version = vsn()' 'version = "${old.version}"'
      '';

      # replace this twice because buildMix copies from $src
      postInstall = ''
        substituteInPlace $out/src/mix.exs --replace-fail 'version = vsn()' 'version = "${old.version}"'
      '';
    });
  };
}
```

**Comment by saleyn** [comment]
Please check the latest committed version.

**Comment by adamcstephens** [comment]
Thank you ❤️
